name: todo_pp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  easy_splash_screen: ^1.0.3
  cupertino_icons: ^1.0.2


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.jpg"





 
flutter:


  uses-material-design: true

  assets:
    - images/

  